app:
  name: frontend
  # group: backend
  replicaCount: 1
  container:
    image: docker.io/tienshawn/student-web-cont:d3e4e127
    port: 80
    imagePullPolicy: Always
    # protocol: TCP
    config: []
    env:
      - key: key
        value: value
  service:
    port: 80
    nodePort: 30007 #web nodePort, access with http://<node-ip>:30007/
